# This is an example mods.toml file. It contains the data relating to the loading mods.
# There are several mandatory fields (#mandatory), and many more that are optional (#optional).
# The overall format is standard TOML format, v0.5.0.
# Note that there are a couple of TOML lists in this file.
# Find more information on toml format here:  https://github.com/toml-lang/toml
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory
license="""(C) Copyright 2020 - QTech Community.
This project is licensed under the CC BY-NC-SA 4.0 license.
See this link for the full license: https://creativecommons.org/licenses/by-nc-sa/4.0/legalcode
"""

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[34,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

# A URL to refer people to when problems occur with this mod
#issueTrackerURL="http://my.issue.tracker/" #optional

# A list of mods - how many allowed here is determined by the individual mod loader

[[mods]] #mandatory
modId="qforgemod" #mandatory
version="1.1-beta9" #mandatory
displayName="QForgeMod: Main Module" #mandatory
#updateJSONURL="http://myurl.me/" #optional
displayURL="https://quintenjungblut.wixsite.com/qplaysoftware/" #optional
#logoFile="qforgemod.png" #optional
credits="Qboi123 (Also known as Qplay123, Xineon)." #optional
authors="Qboi123" #optional
description='''
§nThe§r§o mod for all your needs!§r

§mHello, this is a description, and I do not know what to write here...§r

§mYou don't have to be sad, have some lorem ipsum.§r

§mLorem ipsum dolor sit amet, consectetur adipiscing elit. Sed mollis lacinia magna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Sed sagittis luctus odio eu tempus. Interdum et malesuada fames ac ante ipsum primis in faucibus. Pellentesque volutpat ligula eget lacus auctor sagittis. In hac habitasse platea dictumst. Nunc gravida elit vitae sem vehicula efficitur. Donec mattis ipsum et arcu lobortis, eleifend sagittis sem rutrum. Cras pharetra quam eget posuere fermentum. Sed id tincidunt justo. Lorem ipsum dolor sit amet, consectetur adipiscing elit.§r

§b§l§nCredits:§r
  §l"Modern Sofa" by JustinRustin (Modern Sofa)§r
  Available for download at §nhttps://blockmodelsmodel.com.com//361/ §r

  §l"Club" by Gengar (Club)§r
  §oAvailable for download at https://blockmodels.com.com/model/496/ §r

  §l"Table with tablecloth" by Miep_HD (Table)§r
  §oAvailable for download at https://blockmodels.com.com/model/668/ §r

  §l"Healing Potion" by Gengar (Healing Potion)§r
  §oAvailable for download at https://blockmodels.com.com/model/531/ §r

  §l"Improved PC Gamer" by Giovanni_5656 (Game PC)§r
  §oAvailable for download at https://blockmodels.com.com/model/339/ §r

  §l"Router" by F1ash (Router)§r
  §oAvailable for download at https://blockmodels.com.com/model/331/ §r

  §l"Wooden Box" by F1ash (Crate)§r
  §oAvailable for download at https://blockmodels.com.com/model/330/ §r

§b§l§nOther Mods:§r
  §l=--------------------------=§r
  §oMr. Crayfish Furniture Mod§r
  §l§n=--------------------------=§r
  §lGitHub:§r
   §o https://github.com/MrCrayfish/MrCrayfishFurnitureMod/tree/3a2a73eb43a8fa72b6f621175f7ad84b7ba5306b §r
  §lCurseForge:§r
   §o https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod §r
  §lCurseForge Download:§r
   §o https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod/files/2853267 §r

  §l=--------------------------=§r
  §oQForgeUtils 10§r
  §l§n=--------------------------=§r
  §lGitHub:§r
   §o https://github.com/mekanism/QForgeUtils/tree/f1b7f47dd784649366233ae707f9eef2a2cfe7fb §r
  §lCurseForge:§r
   §o https://www.curseforge.com/minecraft/mc-mods/mekanism §r
  §lCurseForge Download:§r
   §o https://www.curseforge.com/minecraft/mc-mods/mekanism/files/2996531 §r
'''

[[mods]]
modId="qsilentlib"
version="4.9"
displayName="QForgeMod: Silent Library"
updateJSONURL="https://raw.githubusercontent.com/SilentChaos512/SilentLib/1.14/update.json"
description='''
    Shared library for Silent's mods
    '''
[[mods]] #mandatory
# The modid of the mod
modId="qtexturedmodels" #mandatory
# The version number of the mod - there's a few well known ${} variables useable here or just hardcode it
version="1.0-release1" #mandatory
# A display name for the mod
displayName="QForgeMod: Textured Models Module" #mandatory
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="" #optional
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="bc_logo.png" #optional
# A text field displayed in the mod UI
credits="Thanks for many help goes to McJty and the Forge Forum Team" #optional
# A text field displayed in the mod UI
authors="PianoManu, Qboi123" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
This Mod is forked from: https://github.com/PianoManu/BlockCarpentry

Original description:
Fork Mod of Carpenter's Blocks Mod created by Mineshopper (owner of the idea) for older versions of Minecraft.
I created this fork because friends of mine would like to play this mod on 1.15 (and me too).

Right now there is no guide for this mod, so here is one in small form:
- Rightclick on a frame block to give it the texture of the block you clicked it with
- Right-Click with the hammer to get the block back out of the frame (you can change this feature in the config file, so that you only need an empty hand and Sneak-Rightclick)
- For blocks with different textures on each side, you can select the texture you want using the texture wrench
- Let the blocks glow by right-clicking them with glowstone dust or coal/charcoal
- You can also change the appearance of a block by right-clicking it with the chisel and the paintbrush

Have fun!
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.qtexturedmodels]] #optional
# the modid of the dependency
modId="forge" #mandatory
# Does this dependency have to exist - if not, ordering below must be specified
mandatory=true #mandatory
# The version range of the dependency
versionRange="[34,)" #mandatory
# An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
ordering="NONE"
# Side this dependency is applied on - BOTH, CLIENT or SERVER
side="BOTH"
# Here's another dependency
[[dependencies.qtexturedmodels]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3]"
ordering="NONE"
side="BOTH"

# Silent Lib dependencies
[[dependencies.qsilentlib]]
modId="forge"
mandatory=true
versionRange="[33,)"
ordering="NONE"
side="BOTH"
[[dependencies.qsilentlib]]
modId="minecraft"
mandatory=true
versionRange="[1.16.2,)"
ordering="NONE"
side="BOTH"

# QForgeUtils dependencies.
[[dependencies.qforgemod]]
modId="qsilentlib"
mandatory=true
versionRange="4.9"
ordering="NONE"
side="BOTH"
[[dependencies.qforgemod]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[34,)" #mandatory
ordering="NONE"
side="BOTH"
[[dependencies.qforgemod]]
modId="minecraft"
mandatory=true
versionRange="[1.16.3]"
ordering="NONE"
side="BOTH"
